name: "Simple deployment workflow"
on: 
    push: 
        branches: 
            - master
jobs:
    deploy:
        runs-on: self-hosted
        steps: 
            - name: "checksout the repository"
              uses: actions/checkout@v4

            - name: "Log in to Docker"
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: "Resolve the image tag"
              id: tag_generator
              run: |
                echo "deployment_tag=$( git describe --always)" >> $GITHUB_OUTPUT
                echo "image_name=apitest" >> $GITHUB_OUTPUT
                
                


            - name: "Build a Docker Image"
              run: |
                sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag_generator.outputs.image_name }}:${{ steps.tag_generator.outputs.deployment_tag }} .
                sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag_generator.outputs.image_name }}:${{ steps.tag_generator.outputs.deployment_tag }}
               
            - name: "Run the Docker image"
              run: |
                sudo docker run -d --name apitest -e PORT=${{ secrets.PORT }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.tag_generator.outputs.image_name }}:${{ steps.tag_generator.outputs.deployment_tag }}