name: "Simple deployment workflow"
on: 
    push: 
        branches: 
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: "checksout the repository"
              uses: actions/checkout@v4

            - name: "Log in to Docker"
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: "Resolve the image tag"
              run: |
                deployment_tag=$( git describe)

            - name: "Build a Docker Image"
              run: |
                docker build -t apitest:1